// <auto-generated />
namespace JogosDeGuerraModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _0412 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_0412));
        
        string IMigrationMetadata.Id
        {
            get { return "201812041131267_04.12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
