// <auto-generated />
namespace JogosDeGuerraWebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _2911 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2911));
        
        string IMigrationMetadata.Id
        {
            get { return "201811291134003_29.11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
